# Generated by Django 5.0.2 on 2024-03-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooptoday', '0004_remove_gamepost_likes_remove_post_likes_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, to='hooptoday.post'),
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
