# Generated by Django 5.0.2 on 2024-03-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooptoday', '0005_userprofile_liked_posts_delete_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
