# Generated by Django 5.0.2 on 2024-03-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooptoday', '0007_userprofile_liked_game_posts_alter_post_text_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
